### ISSUE TITLE
Enumeração repetida

### ISSUE THREAD

**Issue by Guior** [Guior/Source-Code-Inspection#1]
Enumeração repetida em Fluxo Principal de [CSU03 – Solicitar troco](https://github.com/Guior/Source-Code-Inspection/wiki/Engenharia-de-Requisitos#csu03---solicitar-troco)

![](https://user-images.githubusercontent.com/42626625/159138873-da62034c-81e7-4883-81e5-5b400a7fd301.png)

**Comment by seleonel** [comment]
Corrigido em 25/03
